# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  # SOFLE -----------------------------------
  # ## Firmwares (Dongle + Split)
  # - board: xiao_ble//zmk
  #   shield: Sofle_dongle_central prospector_adapter
  #   cmake-args: -DCONFIG_PROSPECTOR_STATUS_SCREEN_OPERATOR=y
  #   artifact-name: dongle_theme_operator

  # - board: nice_nano//zmk
  #   shield: Sofle_dongle_left
  #   artifact-name: dongle_split_left

  # - board: nice_nano//zmk
  #   shield: Sofle_dongle_right
  #   artifact-name: dongle_split_right

  # ### BLACKLIGHTRELAY -------------------
  - board: xiao_ble//zmk
    shield: Sofle_dongle_central prospector_adapter
    keymap: SOFLE_BlacklightRelay_dongle
    extra-conf: SOFLE_BlacklightRelay_dongle
    cmake-args: -DCONFIG_PROSPECTOR_STATUS_SCREEN_OPERATOR=y
    artifact-name: blacklightrelay_dongle_theme_operator

  - board: nice_nano//zmk
    shield: Sofle_dongle_left
    keymap: SOFLE_BlacklightRelay_dongle
    extra-conf: SOFLE_BlacklightRelay_dongle
    artifact-name: blacklightrelay_split_left

  - board: nice_nano//zmk
    shield: Sofle_dongle_right
    keymap: SOFLE_BlacklightRelay_dongle
    extra-conf: SOFLE_BlacklightRelay_dongle
    artifact-name: blacklightrelay_split_right

  # CORNE -----------------------------------
  # ## Firmwares (Dongle + Split)
  # - board: xiao_ble//zmk
  #   shield: Corne_dongle_central prospector_adapter
  #   keymap: CORNE_AkitsuEcho
  #   extra-conf: CORNE_AkitsuEcho
  #   cmake-args: -DCONFIG_PROSPECTOR_STATUS_SCREEN_FIELD=y
  #   artifact-name: akitsuecho_dongle

  - board: nice_nano//zmk
    shield: Corne_dongle_left
    keymap: CORNE_AkitsuEcho
    extra-conf: CORNE_AkitsuEcho
    artifact-name: akitsuecho_split_left

  - board: nice_nano//zmk
    shield: Corne_dongle_right
    keymap: CORNE_AkitsuEcho
    extra-conf: CORNE_AkitsuEcho
    artifact-name: akitsuecho_split_right
  
  # Generic Corne (Unnamed)
  - board: nice_nano//zmk
    shield: Corne_L nice_epaper Nice_view_config
    keymap: CORNE_AkitsuEcho
    extra-conf: Corne
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: Corne_split_left

  - board: nice_nano//zmk
    shield: Corne_R nice_epaper Nice_view_config
    keymap: CORNE_AkitsuEcho
    extra-conf: Corne
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
    artifact-name: Corne_split_right

  # Resets
  - board: nice_nano//zmk
    shield: settings_reset
    artifact-name: reset_splits

  - board: xiao_ble//zmk
    shield: settings_reset
    artifact-name: reset_dongle
