# 更改键盘默认显示名称
CONFIG_ZMK_KEYBOARD_NAME="BlacklightRelay"
#EC11 enable
# CONFIG_EC11=y
# CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_HID_REPORT_TYPE_NKRO=n
CONFIG_ZMK_DISPLAY=y

#rgb相关配置
# CONFIG_ZMK_RGB_UNDERGLOW=n
# CONFIG_WS2812_STRIP=n
#键盘进入空闲状态时关闭RGB
# CONFIG_ZMK_BACKLIGHT_AUTO_OFF_IDLE=y
# CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y
# CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n
# CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=3
# CONFIG_ZMK_RGB_UNDERGLOW_BRT_MAX=60
# CONFIG_ZMK_RGB_UNDERGLOW_BRT_START=60

CONFIG_PROSPECTOR_USE_AMBIENT_LIGHT_SENSOR=n
CONFIG_PROSPECTOR_FIXED_BRIGHTNESS=50
CONFIG_PROSPECTOR_SHOW_MODIFIERS=y

CONFIG_ZMK_LEADER_MAX_KEYS_PER_SEQUENCE=8
CONFIG_ZMK_LEADER_MAX_SEQUENCES=32

# Workaround: LVGL built-in sprintf conflicts with Zephyr minimal libc
CONFIG_LV_USE_BUILTIN_SPRINTF=n
